feat: add minimum wrapper for compute LRO method
googleapis/nodejs-compute pull request #618
Opened 2021-09-07 23:36 UTC by summer-ji-eng

@google-cloud/gapic-generator v2.5.0
gapic-generator-typescript enables diregapic (compute) library add a minimum wrapper for LRO operation https://github.com/googleapis/gapic-generator-typescript/pull/967

Manually update the surface using the v2.5.0 generator.

2021-09-08 17:03 UTC, alexander-fenster approved these changes

2021-09-08 17:16 UTC, bcoe approved these changes
With a nit, we don't need to manually update version #s.

2021-09-08 17:16 UTC, bcoe commented on package.json
> +  "version": "3.0.0-alpha.4",
Our tooling will update this for you, no need to change here 👍

2021-09-10 22:00 UTC, bcoe requested changes
accidentally checked in `google-cloud-compute-3.0.0.tgz`.

2021-09-13 18:53 UTC, bcoe approved these changes

2021-09-13 20:57 UTC, merged